name: Update Project v2 Item Field
description: Automatically update a field on a GitHub project v2 item
author: nipe0324
branding:
  icon: table
inputs:
  project-url:
    required: true
    description: URL of the project vw to update item field
  github-token:
    required: true
    description: A GitHub personal access token with write access to the project
  field-name:
    required: true
    description: The name of the field to update. Supported field types are `text`, `number`, `date` and `single_select`
  field-value:
    required: true
    description: The value of the field to update.

outputs:
  projectId:
    description: The ID of the GitHub project v2
  contentId:
    description: The ID of the Issues or PRs

runs:
  using: node20
  main: dist/index.js
